### ISSUE TITLE
Routes : l'avant-dernière ligne est-elle utile ?

### ISSUE THREAD

**Issue by tanasz** [Nosmokingboy/yobox#19]
Rails.application.routes.draw do
  root to: 'boxes#index'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :boxes, only: [:new, :create, :index, :show] do
    resources :openings, only: [:create]
  end
  **resources :openings, only: [:edit, :update]**
end

Elle donne accès à **edit** et **update** de openings :
- ceux ci sont explicitement désactivés 2 lignes + haut (avec le only: create)
- sont-ils utiles ? Il ne me semble pas qu'on ait besoin d'une route pour éditer les openings ?

**Comment by Nosmokingboy** [comment]
Salut Anik, 

Je viens de faire la modification.

**Comment by tanasz** [comment]
Bon, j'espère que je n'ai pas dit d'âneries ;-)
Pour info je blablate dans le vide depuis ce matin dans le channel Yobox : soit vous vous en tapez, soit personne n'y est...

**Comment by Nosmokingboy** [comment]
slack is back ;)
